name: Deployment

on:
    push:
      branches: ["main"]

jobs: 
   
    build-frontend: 
        
      name: Build frontend
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up Node18.x
          uses: actions/setup-node@v2
          with:
            node-version: 18.x

        - name: Install dependencies
          working-directory: React-app
          run: npm install

        - name: Run Vitest
          working-directory: React-app
          run: npm test
          env:
            VITE_BASE_URL: ${{secrets.VITE_BASE_URL}}

        - name: Build frontend
          working-directory: React-app
          run: npm run build

        - name: Install Railway CLI
          run: npm i -g @railway/cli

        - name: Deploy
          run: railway up
          env:
            RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
            
        
